/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ldventas;

import javax.swing.JOptionPane;

/**
 *
 * @author luise
 */
public class Ventas extends javax.swing.JPanel {

    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCantidadCompra = new javax.swing.JTextField();
        btnAgregarPV = new javax.swing.JButton();
        btnEliminarPV = new javax.swing.JButton();
        btnCobrarVenta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVentas = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        vent.setBackground(new java.awt.Color(144, 214, 255));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setText("Codigo de producto:");

        txtCodigoP.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtCodigoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoPKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setText("Cantidad:");

        txtCantidadCompra.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtCantidadCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadCompraKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadCompraKeyTyped(evt);
            }
        });

        btnAgregarPV.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnAgregarPV.setText("Agregar");
        btnAgregarPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPVActionPerformed(evt);
            }
        });

        btnEliminarPV.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnEliminarPV.setText("Eliminar");
        btnEliminarPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPVActionPerformed(evt);
            }
        });

        btnCobrarVenta.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnCobrarVenta.setText("Cobrar");
        btnCobrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarVentaActionPerformed(evt);
            }
        });

        tbVentas.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tbVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Precio unitaroio", "Cantidad", "Monto"
            }
        ));
        jScrollPane1.setViewportView(tbVentas);

        javax.swing.GroupLayout ventLayout = new javax.swing.GroupLayout(vent);
        vent.setLayout(ventLayout);
        ventLayout.setHorizontalGroup(
            ventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCodigoP)
                        .addComponent(txtCantidadCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnCobrarVenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarPV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarPV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
        );
        ventLayout.setVerticalGroup(
            ventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidadCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnAgregarPV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarPV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnCobrarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        add(vent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadCompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadCompraKeyPressed
          
    }//GEN-LAST:event_txtCantidadCompraKeyPressed

    private void txtCodigoPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoPKeyTyped
        
    }//GEN-LAST:event_txtCodigoPKeyTyped

    private void btnAgregarPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPVActionPerformed
        String cantidadcompra, codigop;
        cantidadcompra = txtCantidadCompra.getText();
        codigop = txtCodigoP.getText();
        if(cantidadcompra.equals("") || codigop.equals("")){
        JOptionPane.showMessageDialog(null, "Campos vacío ");
        
        }else {
            
            
            
            
            JOptionPane.showMessageDialog(null, "Agregado ");
        
        }
        
    }//GEN-LAST:event_btnAgregarPVActionPerformed

    private void txtCantidadCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadCompraKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese números");
            txtCodigoP.setText(" ");
        }  
    }//GEN-LAST:event_txtCantidadCompraKeyTyped

    private void btnCobrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarVentaActionPerformed
        int op
                = JOptionPane.showConfirmDialog(null, "¿Seguro que quieres cobrar ya?", "CONFIRMACION",
                        JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
           

            
            JOptionPane.showMessageDialog(null, "Imprimiendo nota de venta");
        } else {

            JOptionPane.showMessageDialog(null, "Puedes seguir agregar más productos");

        }//cierre del else
    }//GEN-LAST:event_btnCobrarVentaActionPerformed

    private void btnEliminarPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPVActionPerformed
        int op
                = JOptionPane.showConfirmDialog(null, "¿Seguro que quieres eliminar este producto?", "CONFIRMACION",
                        JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            

            JOptionPane.showMessageDialog(null, "Se ha eliminado correctamente");

        } else {

            JOptionPane.showMessageDialog(null, "No se ha eliminado ningun producto");

        }//cierre del else
    }//GEN-LAST:event_btnEliminarPVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPV;
    private javax.swing.JButton btnCobrarVenta;
    private javax.swing.JButton btnEliminarPV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbVentas;
    private javax.swing.JTextField txtCantidadCompra;
    private javax.swing.JTextField txtCodigoP;
    private javax.swing.JPanel vent;
    // End of variables declaration//GEN-END:variables
}
