/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

//import javax.swing.JOptionPane;
import Controlador.bd.ConexionBD;
import Controlador.bd.Transacciones;
import Modelo.Usuario;
import controlado.*;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author luise
 */
public class VLogin extends javax.swing.JFrame {
    VLogin login;
    Usuario usuario;
    Seguridad seguridad;
    Transacciones transacciones;

    /**
     * Creates new form Login
     */
    public VLogin() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Login");
        this.setResizable(false);
        
               
        
        
        
  
        this.seguridad = new Seguridad();
        this.transacciones = new Transacciones();
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        btnIniciarSesion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        imglogo = new javax.swing.JLabel();
        imgcubos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(12, 192, 223));
        jPanel1.setForeground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contraseña");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 80, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Iniciar seción");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        txtUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtUsuario.setOpaque(true);
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 150, 30));
        jPanel1.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 150, 30));

        btnIniciarSesion.setBackground(new java.awt.Color(255, 102, 196));
        btnIniciarSesion.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Entrar");
        btnIniciarSesion.setBorderPainted(false);
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 210, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 513));

        jPanel2.setBackground(new java.awt.Color(56, 182, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imglogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        jPanel2.add(imglogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        imgcubos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cubos.png"))); // NOI18N
        jPanel2.add(imgcubos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 340, 460));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 376, 513));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
       /* String usu,cont;
        usu = txtUsuario.getText();
        cont = txtContrasena.getText();
        
        if (usu.equals("admin") || cont.equals("123")){
            
             new VMenu().setVisible(true);
        } else {
        
        JOptionPane.showMessageDialog(null, "Contraseña invalida");
        
        }
      */
       
       if (evt.getSource() == btnIniciarSesion) {
            this.usuario = new Usuario();

            //Obtenemos los datos que han ingresado en el VLogin
            String nombreUsuario = txtUsuario.getText();
            char[] contrasenaChars = txtContrasena.getPassword();            
            String contrasena = this.seguridad.getHashMD5(new String(contrasenaChars));  
            
            //JOptionPane.showMessageDialog(null, contrasena);
            
            this.usuario.setNombreUsuario(nombreUsuario);
            this.usuario.setContrasena(contrasena);            
            
            //validamos la sesión
            if (this.transacciones.validarSesion(usuario)) {
                
               
                this.dispose();
                new VMenu().setVisible(true);  
                
                
               
                                                
            } 
            
        } 
        
        
        
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    
        
        
//    public static void main(String[] args) {
//        
//         
//        
//       new VLogin().setVisible(true);
//    
//    
//    
//    } // close main

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel imgcubos;
    private javax.swing.JLabel imglogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPasswordField txtContrasena;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void setVisible(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
