/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ldsystem;

import java.awt.BorderLayout;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JOptionPane;

/**
 *
 * @author luise
 */
public class Alumnas extends javax.swing.JPanel {

    /**
     * Creates new form Inscripcion
     */
    public Alumnas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnIns = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAlumnas = new javax.swing.JTable();
        tbAgregarAlumna = new javax.swing.JButton();
        tbnEliminarAlumna = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnIns.setBackground(new java.awt.Color(144, 214, 255));

        tbAlumnas.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tbAlumnas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre"
            }
        ));
        jScrollPane1.setViewportView(tbAlumnas);

        tbAgregarAlumna.setBackground(new java.awt.Color(85, 142, 213));
        tbAgregarAlumna.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tbAgregarAlumna.setText("Agregar");
        tbAgregarAlumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbAgregarAlumnaActionPerformed(evt);
            }
        });

        tbnEliminarAlumna.setBackground(new java.awt.Color(85, 142, 213));
        tbnEliminarAlumna.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tbnEliminarAlumna.setText("Eliminar");
        tbnEliminarAlumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnEliminarAlumnaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnInsLayout = new javax.swing.GroupLayout(pnIns);
        pnIns.setLayout(pnInsLayout);
        pnInsLayout.setHorizontalGroup(
            pnInsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbAgregarAlumna, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(tbnEliminarAlumna, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        pnInsLayout.setVerticalGroup(
            pnInsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInsLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnInsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbAgregarAlumna, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbnEliminarAlumna, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        add(pnIns, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tbAgregarAlumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbAgregarAlumnaActionPerformed
        
        //Manda a llamar el JPanel de Inscripcion
        Inscripcion ins1 = new Inscripcion();
        ins1.setSize(880,380);
        ins1.setLocation(0,0);

        pnIns.removeAll();
        pnIns.add(ins1, BorderLayout.CENTER);
        pnIns.revalidate();
        pnIns.repaint();
    }//GEN-LAST:event_tbAgregarAlumnaActionPerformed

    private void tbnEliminarAlumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnEliminarAlumnaActionPerformed
        int op
                = JOptionPane.showConfirmDialog(null, "¿Seguro que quieres eliminar esta alumna?", "CONFIRMACION",
                        JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            

            JOptionPane.showMessageDialog(null, "Se ha eliminado correctamente");

        } else {

            JOptionPane.showMessageDialog(null, "No se ha eliminado ningun dato");

        }//cierre del else
    }//GEN-LAST:event_tbnEliminarAlumnaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnIns;
    private javax.swing.JButton tbAgregarAlumna;
    private javax.swing.JTable tbAlumnas;
    private javax.swing.JButton tbnEliminarAlumna;
    // End of variables declaration//GEN-END:variables
}
