/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ldsystem;

import java.awt.BorderLayout;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author luise
 */
public class NivelAlumna extends javax.swing.JPanel {

    DefaultTableModel modelo;
    public static int idSeleccionado;    
    
    /**
     * Creates new form Alumnas
     */
    public NivelAlumna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nivelAlumn = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNivel = new javax.swing.JTable();
        btnSeleccionarN = new javax.swing.JButton();

        setName(""); // NOI18N
        setLayout(new java.awt.BorderLayout());

        nivelAlumn.setBackground(new java.awt.Color(144, 214, 255));

        tbNivel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tbNivel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nivel", "Horario"
            }
        ));
        tbNivel.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tbNivel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNivelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbNivel);

        btnSeleccionarN.setBackground(new java.awt.Color(85, 142, 213));
        btnSeleccionarN.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnSeleccionarN.setText("Seleccionar");
        btnSeleccionarN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nivelAlumnLayout = new javax.swing.GroupLayout(nivelAlumn);
        nivelAlumn.setLayout(nivelAlumnLayout);
        nivelAlumnLayout.setHorizontalGroup(
            nivelAlumnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nivelAlumnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSeleccionarN, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        nivelAlumnLayout.setVerticalGroup(
            nivelAlumnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nivelAlumnLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSeleccionarN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        add(nivelAlumn, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarNActionPerformed
        Alumnas al1 = new Alumnas();
        al1.setSize(880,380);
        al1.setLocation(0,0);

        nivelAlumn.removeAll();
        nivelAlumn.add(al1, BorderLayout.CENTER);
        nivelAlumn.revalidate();
        nivelAlumn.repaint();
    }//GEN-LAST:event_btnSeleccionarNActionPerformed

    private void tbNivelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNivelMouseClicked
        
    }//GEN-LAST:event_tbNivelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionarN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel nivelAlumn;
    private javax.swing.JTable tbNivel;
    // End of variables declaration//GEN-END:variables
}
